### ISSUE TITLE
issue with protobuf-mode

### ISSUE THREAD

**Issue by mjhoy** [nix-community/emacs-overlay#26] opened 2020-05-09 13:10 UTC
Installing `protobuf-mode` from melpa-stable with the the latest overlay (94ac129125ddf93fc2ef683b8220152af416a992), I get the following error:

```
building '/nix/store/gbfpcs5mzxmvl58960mh9id0ldqzhy3v-emacs-protobuf-mode-3.12.0.-1.1.drv'...
unpacking sources
unpacking source archive /nix/store/27i7nj087gb4cr9as283f3wczzkvwxkx-source
source root is source
patching sources
configuring
no configure script, doing nothing
building
Invalid version syntax: `3.12.0.-1.1'
builder for '/nix/store/gbfpcs5mzxmvl58960mh9id0ldqzhy3v-emacs-protobuf-mode-3.12.0.-1.1.drv' failed with exit code 255
cannot build derivation '/nix/store/99x2id2in0i6jcnnjf43znlf8lg59wgr-emacs-with-packages-26.3.drv': 1 dependencies couldn't be built
```

is this an issue with protobuf-mode?

**Comment by adisbladis** [comment] 2020-05-09 14:07
It looks to me like a problem with Melpa silently stripping the `rc` bits from the version number: https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0-rc1 & https://stable.melpa.org/#/protobuf-mode.

I don't think this is the desired behaviour.. cc @purcell

**Comment by purcell** [comment] 2020-05-10 09:54
I don't think it's a matter of silently stripping, exactly: when Emacs' version functions converts versions with suffixes like `-rc` `-git` etc. to numeric "version arrays", a `-1` in the fourth version number component is used for those "pre" releases. I wonder how GNU ELPA handles this... I'll have to have a look in `package-build` ([here](https://github.com/melpa/package-build/blob/master/package-build.el) to see if we can preserve this info.

**Comment by purcell** [comment] 2020-05-12 03:15
Okay, so... you may be surprised to hear that this is not broken on the Emacs / MELPA side. The metadata for the package contains the numeric version list - `(3 12 0 -1 1)` - and then it is Emacs itself (via `package.el`) which constructs the download URL. Installing this package from within Emacs works fine, even though the version URL is an ugly one under the covers: https://stable.melpa.org/packages/protobuf-mode-3.12.0.-1.1.el

So it's working as designed, but obviously Nix has different (and more reasonable) ideas about what constitutes a reasonable version number.

In theory we (MELPA) support any version parseable by `version-to-list`:
```
   Version String    Version as a List of Integers
   ".5"              (0 5)
   "0.9 alpha"       (0  9 -3)
   "0.9AlphA1"       (0  9 -3 1)
   "0.9snapshot"     (0  9 -4)
   "1.0-git"         (1  0 -4)
   "1.0.7.5"         (1  0  7 5)
   "1.0.cvs"         (1  0 -4)
   "1.0PRE2"         (1  0 -1 2)
   "1.0pre2"         (1  0 -1 2)
   "22.8 Beta3"      (22 8 -2 3)
   "22.8beta3"       (22 8 -2 3)
```
so you could get `-1`, `-2`, `-3` or `-4` in a version field. I'm not sure what Nix allows in its version strings, but if it supports "rc" or similar suffixes, then some degree of mangling might be needed to conver Emacs version lists as above into Nix version strings.

**Comment by purcell** [comment] 2020-05-12 03:19
There's perhaps also an argument that MELPA Stable should not include such pre-releases in the first place...

**Comment by purcell** [comment] 2020-05-12 03:24
There's apparently a var which governs this parsing:
```
version-regexp-alist is a variable defined in ‘subr.el’.
Its value is
(("^[-._+ ]?snapshot$" . -4)
 ("^[-._+]$" . -4)
 ("^[-._+ ]?\\(cvs\\|git\\|bzr\\|svn\\|hg\\|darcs\\)$" . -4)
 ("^[-._+ ]?alpha$" . -3)
 ("^[-._+ ]?beta$" . -2)
 ("^[-._+ ]?\\(pre\\|rc\\)$" . -1))

  This variable may be risky if used as a file-local variable.

Documentation:
Specify association between non-numeric version and its priority.

This association is used to handle version string like "1.0pre2",
"0.9alpha1", etc.  It’s used by ‘version-to-list’ (which see) to convert the
non-numeric part of a version string to an integer.  For example:

   String Version    Integer List Version
   "0.9snapshot"     (0  9 -4)
   "1.0-git"         (1  0 -4)
   "1.0.cvs"         (1  0 -4)
   "1.0pre2"         (1  0 -1 2)
   "1.0PRE2"         (1  0 -1 2)
   "22.8beta3"       (22 8 -2 3)
   "22.8 Beta3"      (22 8 -2 3)
   "0.9alpha1"       (0  9 -3 1)
   "0.9AlphA1"       (0  9 -3 1)
   "0.9 alpha"       (0  9 -3)

Each element has the following form:

   (REGEXP . PRIORITY)
```

**Comment by adisbladis** [comment] 2020-05-16 08:16
Since the `protobuf-mode` build is [no longer failing](https://hydra.nix-community.org/build/164094) I'm gonna go ahead and close this issue.

**Closed by adisbladis** 2020-05-16 08:16 UTC

**Comment by mjhoy** [comment] 2020-07-17 11:58
I'm again getting a failure with protobuf-mode :(

```
Invalid version syntax: `4.0.0.-1.1'
builder for '/nix/store/pdp33r1hnchr6igqsr1mbpzncarx5163-emacs-protobuf-mode-4.0.0.-1.1.drv' failed with exit code 255
```
