### ISSUE TITLE
automatic update not working

### ISSUE THREAD

**Issue by wfranzini** [nix-community/emacs-overlay#375] opened 2023-12-21 12:10 UTC
Since a week the automatic update of this repository has stopped.

The tasks timeout after 6 hours.

**Comment by miangraham** [comment] 2023-12-21 22:23
From a recent failure:

```
2023-12-20T16:14:13.2567213Z Requested labels: ubuntu-latest
...
2023-12-20T17:06:14.4931009Z INFO: cmake-mode: prefetched repository 1eed682d7cca9bb2c2b0709a6c3202a3b08613b2 166i1j8xlv4m82g2dyjl02kdx3yybsyd3jv3dq6f7n94widv3yq6
2023-12-20T22:14:31.5730926Z ##[error]The operation was canceled.
```

Looks like normal movement for close to an hour, then progress stalls with no obvious error before eventually timing out. Feels vaguely like getting hit by rate-limiting or some other form of broken checkout without the error getting surfaced in the log output.

**Comment by lelit** [comment] 2023-12-22 10:58
[Last successful run](https://github.com/nix-community/emacs-overlay/actions/runs/7184223319) took 38 minutes, some before that took 1 hour and half, rarely 2 hours.
Since that run, all were canceled after *six* hours: what could cause such a large jump?

**Comment by wfranzini** [comment] 2023-12-23 10:50
@adisbladis  do you have the time to look into this? Thanks

**Comment by Vonfry** [comment] 2023-12-24 04:48
Thanks! CI updated repos today.

**Comment by Vonfry** [comment] 2023-12-24 07:41
elpa has been fixed, but the auto-update of melpa also failed.

**Comment by leungbk** [comment] 2023-12-24 11:19
> elpa has been fixed, but the auto-update of melpa also failed. Is this issue relative to [NixOS/nixpkgs#276401](https://github.com/NixOS/nixpkgs/pull/276401)?


They are unrelated. The other PR I made patches an issue that surfaced in Emacs commit bb5399e3cd75450db6db9b3c5829f7bd87ca1308, made around Dec 22; the six-hour MELPA thing started around Dec 13.

**Comment by Vonfry** [comment] 2023-12-28 23:51
NixOS/nixpkgs#272984 was merged around Dec 13 into nixos-unstable, which may be the reason of 6 hours ci. `update-melpa.el` may have some issues on emacs 29.

**Comment by Vonfry** [comment] 2023-12-29 03:57
I made a pr (NixOS/nixpkgs#277455) to fix this issue. The main problem is caused by wrong http response parsing in http-get for me on local emacs.
The update-melpa can work correctly on my local emacs interactively with this patch.

**Closed** 2024-01-03 15:36 UTC
