### ISSUE TITLE
Missing cache after gcc was merged

### ISSUE THREAD

**Issue by jacksonludwig** [nix-community/emacs-overlay#145] opened 2021-05-03 13:46 UTC
Since #143 I have not been able to hit the cache. I am following the nixos-unstable branch. 

I don't think it's on my end as I haven't changed my config in months, and I had consistently hit the cache for that time.

Anyone else noticing this?

**Comment by spacekitteh** [comment] 2021-05-05 04:03
I hit it once, this morning. Missing it again now.

The cache isn't being updated often enough.

**Comment by adisbladis** [comment] 2021-05-06 13:15
The cache is always going to lag a bit behind nixpkgs channel progressions, this is just an unfortunate fact.

**Comment by jacksonludwig** [comment] 2021-05-14 02:48
Well I have hit the cache since, but it really seems way more inconsistent than before the merge. I'll leave it open but since not many others seem to have the same problem I understand if the issue should be closed.

**Comment by spacekitteh** [comment] 2021-05-18 21:34
Perhaps the repo update for the git version should be performed less often, like, once a day?

**Comment by adisbladis** [comment] 2021-05-18 21:46
I'm closing this since this is not a bug, and the cache is simply a convenience.

If you want bleeding edge packages you're expected to rebuild a fair bit more often.

**Closed by adisbladis** 2021-05-18 21:46 UTC
