### ISSUE TITLE
#282 breaks image support in emacsPgtk

### ISSUE THREAD

**Issue by accelbread** [nix-community/emacs-overlay#288] opened 2022-12-22 20:17 UTC
On the prior commit before merging https://github.com/nix-community/emacs-overlay/pull/282 (233d2937a35960459f8d0958548fccf67c060330) and before, the contents of `system-configuration-options` is:

"--prefix=/nix/store/z1j638ahzrmmff72zfz7c9g1kdfw5gvl-emacs-pgtk-20221218.0 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-cairo --with-native-compilation --with-pgtk"

On commit 838a1eb25552b93841ba025c02c2a98062fcf22f and after, `system-configuration-options` now is:

"--prefix=/nix/store/00r18k92w7jmm5p3sgafnyysa76pc9mq-emacs-pgtk-20221218.0 --disable-build-details --with-modules --with-x=no --with-xpm=no --with-jpeg=no --with-png=no --with-gif=no --with-tiff=no --with-native-compilation --with-pgtk"

As you can see, the build now does not include image support. Though not in the options, svg support is also no longer built in.

**Comment by leungbk** [comment] 2022-12-23 00:26
The person who fixed this in upstream nixpkgs neglected to backport to the 22.11 branch. I have tried to initiate the backport PR, though it may take a few minutes to trigger.

**Comment by leungbk** [comment] 2022-12-23 00:35
https://github.com/NixOS/nixpkgs/pull/207347

**Comment by luftmensch-luftmensch** [comment] 2023-01-08 17:29
[NixOS/nixpkgs#207347](https://github.com/NixOS/nixpkgs/pull/207347) is merged c:

**Comment by luftmensch-luftmensch** [comment] 2023-01-09 13:43
@leungbk  sorry if I reopen it. I'm currently having the same problem (no image support on emacs), even if I've update the flake revision of both nixpkgs (22.11) and emacs-overlay. I've checked also the latest [evaluation](https://hydra.nix-community.org/build/1377807) (the change needed to build emacs with image support on the nixpkgs repository are there), but I still have no image support. I'm missing something?

**Comment by leungbk** [comment] 2023-01-09 14:05
@luftmensch-luftmensch I can't reproduce on nixpkgs `origin/release-22.11`. Could you post your flake? `C-h v system-configuration-options` gives me `"--prefix=/nix/store/5864m14kldy0d56qnbwznpcqpczi5xfb-emacs-pgtk-20230108.0 --disable-build-details --with-modules --with-pgtk --with-native-compilation"`.

**Comment by leungbk** [comment] 2023-01-09 14:13
Hmm, looks like the rev you're using (https://github.com/luftmensch-luftmensch/Nixos/blob/261657e868d26c3719e81ff4b9d3e24a6a6d9710/flake.lock#L522) doesn't yet contain the backport commit. So we may need to wait a bit longer before the channel updates.

**Comment by luftmensch-luftmensch** [comment] 2023-01-09 14:14
Hmmm, strange. I picked from hydra and in the nixpkgs input i've already see that the change is present

**Comment by leungbk** [comment] 2023-01-09 14:41
At the time of writing, the `nixos-21.11` channel is on `8c54d842d9544361aac5f5b212ba04e4089e8efe`, which does not contain the backport commit. The nixpkgs rev I see in your `flake.lock` doesn't contain the backport commit either. Your build artifacts will not, in general, use the same nixpkgs rev as the overlay hydra.

**Comment by luftmensch-luftmensch** [comment] 2023-01-09 15:50
Do you know if there is a way to track if the backport commit is landed?

**Comment by leungbk** [comment] 2023-01-10 23:26
You can check status.nixos.org.

The channel has now updated to contain the backport, so I'm closing.

**Closed by leungbk** 2023-01-10 23:26 UTC
